// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY651UZ4atGMw-EyDOS4YuVun3mEpClLE',
    appId: '1:892428853686:web:5f85e6c02fdc79cc772117',
    messagingSenderId: '892428853686',
    projectId: 'fire-app-c1778',
    authDomain: 'fire-app-c1778.firebaseapp.com',
    storageBucket: 'fire-app-c1778.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw30iRoZS5UAapLmuN0N_ZM-fVlVlADvY',
    appId: '1:892428853686:android:9cd9b0ed4d9cbf4e772117',
    messagingSenderId: '892428853686',
    projectId: 'fire-app-c1778',
    storageBucket: 'fire-app-c1778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbEh5sZAmqb_-HNZdmqAnwuln8-rW5n6k',
    appId: '1:892428853686:ios:c88b1f5e772ca115772117',
    messagingSenderId: '892428853686',
    projectId: 'fire-app-c1778',
    storageBucket: 'fire-app-c1778.appspot.com',
    iosClientId: '892428853686-odardm39ibmjgb7lbbkd5q73g5dc4j6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireApp',
  );
}
